# Generated by Django 4.2.13 on 2024-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='айді книги'),
        ),
    ]
