# Generated by Django 4.2.13 on 2024-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.CharField(null=True, verbose_name='IMAGE'),
        ),
    ]
